/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

  GtkWidget *window1;
  GtkWidget *window2;
  GtkWidget *window3;
  gint index_of_active_client;
  GtkWidget *textview1;


GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_window3 (void);
