/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#include <gtk/gtk.h>

GtkWidget* create_window1 (void);

gboolean cb_timeout( gpointer data );
gboolean exec_timeout( gpointer data );
gpointer thread_func( gpointer data );

void * updater(void *args);

void set_execution_view(char *message);

void set_command_view(char *message);

void clear_command_window();


